# Puerto de microservicio acceso_service
server.port=8085

# Nombre de la aplicación
spring.application.name=acceso-service

# URL de conexión a la base de datos propia de acceso_service
spring.datasource.url=jdbc:mysql://localhost:3306/acceso_db?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true

# Usuario de MySQL
spring.datasource.username=dev_user

# Password del usuario de MySQL
spring.datasource.password=dev123

# Evita que Hibernate cree o modifique tablas automáticamente
spring.jpa.hibernate.ddl-auto=none

# Muestra las consultas SQL ejecutadas en consola
spring.jpa.show-sql=true

# Formatea las consultas SQL mostradas en consola
spring.jpa.properties.hibernate.format_sql=true

# Activa Flyway para manejar migraciones SQL del microservicio
spring.flyway.enabled=true

# Ruta donde Flyway buscará los scripts de migración
spring.flyway.locations=classpath:db/migration

# URL base del microservicio usuario_service
app.services.usuario.base-url=http://localhost:8081/api/v1/usuarios

# URL base del microservicio vehiculo_service
app.services.vehiculo.base-url=http://localhost:8082/api/v1/vehiculos

# URL base del microservicio plaza_service
app.services.plaza.base-url=http://localhost:8083/api/v1/plazas

# Tiempo máximo para conectar con otros microservicios, en milisegundos
app.services.connect-timeout-ms=3000

# Tiempo máximo para esperar respuesta desde otros microservicios, en milisegundos
app.services.read-timeout-ms=5000

# Clave secreta para validar JWT
# Debe ser la misma usada por auth_service
jwt.secret=clave_estacionamientos

# Muestra detalle de Spring Security durante desarrollo
logging.level.org.springframework.security=DEBUG

# Muestra detalle de las clases propias de acceso_service durante desarrollo
logging.level.cl.duoc.fullstack1.grupo11.estacionamientos.acceso_service=DEBUG

# Permite ver mensajes de error en respuestas durante desarrollo
server.error.include-message=always

# Permite ver errores de validación en respuestas durante desarrollo
server.error.include-binding-errors=always