server.port=8089

spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

app.services.plaza.base-url=http://plaza-service:8083/api/v1/plazas
app.services.movimiento.base-url=http://movimiento-service:8086/api/v1/movimientos
app.services.connect-timeout-ms=3000
app.services.read-timeout-ms=5000

jwt.secret=clave_estacionamientos
jwt.expiration=3600000
