spring.application.name=UsuarioService (dev)

#Driver que usara para conectarse a la BBDD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Define como conectarse a la base de datos
spring.datasource.url=jdbc:oracle:thin:@usuarioestacionamientobbdd_high?TNS_ADMIN=/home/fernandezf-it/Escritorio/ProyectosJava/Estacionamientos/Wallet_usuarioEstacionamientoBBDD/

#Usuario BBDD
spring.datasource.username=ADMIN

#PASS BBDD
spring.datasource.password=UsuarioEstacionamiento_V1

#Estrategia de creacion de tablas (none,update,create,create-drop)
spring.jpa.hibernate.ddl-auto=none

#Muestra en consola las consultas SQL que ejcuta Hibernate
spring.jpa.show-sql=true

#Formatear SQL en consola
spring.jpa.properties.hibernate.format_sql=true

#Dialecto de Hibernate, le dice como generar el SQL para Oracle
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

#Indica que puerto usara el microservicio
server.port=8081

