server.port=8087

spring.datasource.url=jdbc:mysql://localhost:3306/liberacion_db?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
spring.datasource.username=dev_user
spring.datasource.password=dev123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.services.plaza.base-url=http://localhost:8083/api/v1/plazas
app.services.plaza.connect-timeout-ms=3000
app.services.plaza.read-timeout-ms=5000

app.services.movimiento.base-url=http://localhost:8086/api/v1/movimientos
app.services.connect-timeout-ms=3000
app.services.read-timeout-ms=5000

jwt.secret=clave_estacionamientos
jwt.expiration=3600000

# Documentación en Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Configuración Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
