# Puerto de microservicio cierre_service
server.port=8088

# Nombre de la aplicación
spring.application.name=cierre-service

# URL de conexión a la base de datos propia de cierre_service
spring.datasource.url=jdbc:mysql://localhost:3306/cierre_db?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true

# Usuario de MySQL
spring.datasource.username=dev_user

# Password del usuario de MySQL
spring.datasource.password=dev123

# Evita que Hibernate cree o modifique tablas automáticamente
spring.jpa.hibernate.ddl-auto=none

# Muestra las consultas SQL ejecutadas en consola
spring.jpa.show-sql=true

# Formatea las consultas SQL mostradas en consola
spring.jpa.properties.hibernate.format_sql=true

# Activa Flyway para manejar migraciones SQL
spring.flyway.enabled=true

# Ruta donde Flyway buscará los scripts de migración
spring.flyway.locations=classpath:db/migration

# URL base del microservicio plaza_service
app.services.plaza.base-url=http://localhost:8083/api/v1/plazas

# URL base del microservicio reserva_service
app.services.reserva.base-url=http://localhost:8084/api/v1/reservas

# URL base del microservicio reporte_service
app.services.reporte.base-url=http://localhost:8089/api/v1/reportes

# Tiempo máximo para conectar con otros microservicios, en milisegundos
app.services.connect-timeout-ms=3000

# Tiempo máximo para esperar respuesta desde otros microservicios, en milisegundos
app.services.read-timeout-ms=5000

# Clave secreta para validar JWT
# Debe ser la misma usada por auth_service
jwt.secret=clave_estacionamientos

# Muestra detalle de Spring Security durante desarrollo
logging.level.org.springframework.security=DEBUG

# Muestra detalle de las clases propias de cierre_service durante desarrollo
logging.level.cl.duoc.fullstack1.grupo11.estacionamientos.cierre_service=DEBUG

# Permite ver mensajes de error en respuestas durante desarrollo
spring.web.error.include-message=always

# Permite ver errores de validación en respuestas durante desarrollo
spring.web.error.include-binding-errors=always

# Documentación Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Configuración Eureka

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info