# Puerto de microservicio auth_service
server.port=8080

# Nombre de la aplicación
spring.application.name=auth-service

# Desactiva la autoconfiguración de base de datos, JPA/Hibernate y Flyway
# Auth_service es la excepción: no tendrá base de datos propia
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

# URL base del microservicio usuario_service
app.services.usuario.base-url=http://localhost:8081/api/v1/usuarios

# Tiempo máximo para conectar con usuario_service, en milisegundos
app.services.usuario.connect-timeout-ms=3000

# Tiempo máximo para esperar respuesta desde usuario_service, en milisegundos
app.services.usuario.read-timeout-ms=5000

# Clave secreta para firmar el JWT
# Mantener la misma jwt.secret en todos los microservicios que validen tokens
jwt.secret=clave_estacionamientos

# Tiempo de duración del token en milisegundos, 3600000 = 1 hora
jwt.expiration=3600000

# Muestra detalle de Spring Security en consola durante desarrollo
logging.level.org.springframework.security=DEBUG

# Muestra detalle de las clases propias de auth_service durante desarrollo
logging.level.cl.duoc.fullstack1.grupo11.estacionamientos.auth_service=DEBUG

# Permite ver mensajes de error en respuestas durante desarrollo
spring.web.error.include-message=always

# Permite ver errores de validación en respuestas durante desarrollo
spring.web.error.include-binding-errors=always

# Documentación Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Config Eureka

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.status-page-url-path=/doc/swagger-ui.html

management.endpoints.web.exposure.include=health,info